#!/bin/bash

cd /tmp
rm -Rf a b
mkdir -p a/c
cd /tmp/a
pijul init

cat << EOF > /tmp/a/c/a
A
B
C
D
E
EOF

pijul add c/a
echo "----------- Record a"
pijul record


cd /tmp
echo "----------- Get a b"
pijul get a b

cd /tmp/b
cat << EOF > /tmp/b/c/b
A
EOF

pijul add c/b
echo "----------- Record b"
pijul record

cd /tmp/a
echo "----------- Remove a: c"
pijul remove c
echo "----------- Record a"
pijul record

cd /tmp/a
pijul pull ../b

dot -Tpdf -o /tmp/a/a.pdf /tmp/a/debug
dot -Tpdf -o /tmp/b/b.pdf /tmp/b/debug
