#!/bin/bash

rm -Rf /tmp/alice /tmp/bob

mkdir -p /tmp/alice/blibli/blublu
cd /tmp/alice
pijul init

echo "blabla" > /tmp/alice/blibli/blublu/blabla
pijul add blibli/blublu/blabla
echo "--------------- Initial record in a"
pijul record -a --author "x" -m "msg"

cd /tmp
echo "--------------- Get a b"
pijul clone alice bob

cd /tmp/bob
pijul mv blibli xyzw
#echo "blibli" > /tmp/bob/bbb
#pijul add bbb
echo "--------------- Record in b"
pijul record -a --author "x" -m ""
echo "--------------- /record in b"

cd /tmp/alice
echo "--------------- Record in a"
pijul mv blibli blzaaaa
pijul record -a --author "x" -m ""
echo "--------------- /record in a"
echo "--------------- Final pull from a"
pijul pull ../bob -a
#find .

cd /tmp/alice/*/blublu
pijul mv blabla main.c
pijul record -a -m "move" --author ""

dot -Tpdf -o /tmp/alice/a.pdf /tmp/alice/debug
dot -Tpdf -o /tmp/bob/b.pdf /tmp/bob/debug
