#!/bin/bash

cd /tmp
rm -Rf a b c
mkdir a
cd /tmp/a
pijul init

cat << EOF > /tmp/a/a
A
B
C
D
E
F
G
EOF

pijul add a
pijul record


cat << EOF > /tmp/a/a
A
B
C
E
F
G
EOF
pijul record


cat << EOF > /tmp/a/a
A
B
G
EOF
pijul record

dot -Tpdf -o /tmp/a/test.pdf debug
