#!/bin/bash

cd /tmp
rm -Rf a b
mkdir a
cd /tmp/a
pijul init

cat << EOF > /tmp/a/a
A
B
C
D
E
EOF

pijul add a
pijul record

cd /tmp
pijul get a b

cd b
cat << EOF > /tmp/b/a
A
B
C
X
D
E
EOF
pijul record

cd /tmp/a
cat << EOF > /tmp/a/a
A
E
EOF
pijul record
pijul pull ../b

cd /tmp/b
pijul pull ../a

dot -Tpdf -o /tmp/a/test.pdf /tmp/a/debug
dot -Tpdf -o /tmp/b/test.pdf /tmp/b/debug
