#!/bin/bash

RECORD_FLAGS=-a
PULL_FLAGS=-a
PUSH_FLAGS=-a

cd /tmp
rm -Rf a b http

#scp $(which pijul) localhost:/usr/local/bin/pijul
mkdir a
cd a
pijul init

cd /tmp/a
cat << EOF > /tmp/a/file
X
Y
EOF

pijul add file
echo "----------- Record a"
pijul record $RECORD_FLAGS


cd /tmp
echo "----------- Cloning"
pijul clone a localhost:/tmp/b

rm -Rf /var/www/html/bla
pijul clone b /var/www/html/bla/bli

cd /tmp
pijul clone http://localhost/bla/bli http
echo "-----------"
cat /tmp/http/file
echo "-----------"


echo "-----------"
cat /tmp/b/file
echo "-----------"

cd /tmp/a
cat << EOF > /tmp/a/file
X
U
Y
EOF
pijul record $RECORD_FLAGS
cd /tmp/a
pijul push localhost:/tmp/b $PUSH_FLAGS

echo "-----------"
cat /tmp/b/file
echo "-----------"


cd /tmp/a/
cat << EOF > /tmp/a/file
X
blabla
Y
EOF
pijul record $RECORD_FLAGS

echo "pushing"
pijul push /tmp/b $PUSH_FLAGS
echo "-----------"
cat /tmp/b/file
echo "-----------"

cd /tmp/b/
cat << EOF > /tmp/b/file
X
blabla
Y
encore un coup
EOF
pijul record $RECORD_FLAGS

cd /tmp/a
echo "pulling"
pijul pull localhost:/tmp/b $PULL_FLAGS
echo "-----------"
cat /tmp/a/file
echo "-----------"

dot -Tpdf -o /tmp/a/a.pdf /tmp/a/debug


pijul push /var/www/html/bla/bli $PUSH_FLAGS

cd /tmp/http
pijul pull http://localhost/bla/bli $PULL_FLAGS
echo "-----------"
cat /tmp/http/file
echo "-----------"
